"""
Match-coupled, career-gated Elo rating engine for List A / ODI cricket.

This is a data-source-agnostic extraction of the Elo builder originally
developed against the ECB data lake (see the dissertation notebooks in
Diss/Code/). It takes two already-loaded pandas DataFrames (batting and
bowling ball-by-ball/innings records) instead of querying a database
directly, so the exact same algorithm can run against either:

  - real ECB data (loaded elsewhere, e.g. via a private data_source module
    that is NOT part of this container), or
  - the synthetic sample data generated by scripts/generate_sample_data.py

Required columns
-----------------
bat_df:
    match_id, start_date, season, player_id, player_name,
    team_id, opposition_team_id, batting_order_position,
    runs, balls_faced, delivery_over_no

bowl_df:
    match_id, start_date, player_id, player_name,
    team_id, opposition_team_id,
    runs, balls, delivery_over_no
"""

from collections import defaultdict

import numpy as np
import pandas as pd


def build_elo_match_coupled(
    bat_df: pd.DataFrame,
    bowl_df: pd.DataFrame,
    elo_start: float = 1500.0,
    scale: float = 360.0,
    season_regress: float = 0.22,
    min_career_balls: int = 12,       # career-total balls gate before Elo moves
    per_match_min_balls=None,          # optional tiny per-match floor; None disables
    k_min: float = 6.0,
    k_max: float = 40.0,
    max_delta: float = 35.0,
    form_window: int = 5,
) -> pd.DataFrame:
    """
    Build match-coupled Elo ratings for batting and bowling.

    - Ratings only move once a player has at least `min_career_balls`
      career balls (tracked separately for batting and bowling).
    - Before reaching the gate, rows are recorded but delta=0.
    - Elo is opponent-adjusted (avg current Elo of the opposing bowlers/
      batters faced that match) and season-regressed toward `elo_start`
      at each player's first appearance in a new season.
    """
    bat = bat_df.copy()
    bowl = bowl_df.copy()

    bat["start_date"] = pd.to_datetime(bat["start_date"])
    bowl["start_date"] = pd.to_datetime(bowl["start_date"])

    # Season normalisation
    if "season" not in bat.columns:
        bat["season"] = bat["start_date"].dt.year
    bat["season"] = bat["season"].astype(float).fillna(bat["start_date"].dt.year).astype(int)
    bowl["season"] = bowl["start_date"].dt.year

    # Phase labels (over-based)
    bat["phase"] = pd.cut(bat["delivery_over_no"], bins=[0, 10, 40, 50], labels=["Powerplay", "Middle", "Death"])
    bowl["phase"] = pd.cut(bowl["delivery_over_no"], bins=[0, 10, 40, 50], labels=["Powerplay", "Middle", "Death"])

    # Baselines
    bat["rpb"] = bat["runs"] / bat["balls_faced"]
    bowl["rpb_conceded"] = bowl["runs"] / bowl["balls"]

    pos_baseline = bat[bat["balls_faced"] > 0].groupby(["season", "batting_order_position"], observed=False)["rpb"].mean().to_dict()
    bat_league_baseline = bat[bat["balls_faced"] > 0].groupby("season", observed=False)["rpb"].mean().to_dict()
    bowl_league_baseline = bowl[bowl["balls"] > 0].groupby("season", observed=False)["rpb_conceded"].mean().to_dict()
    phase_bat_baseline = bat[bat["balls_faced"] > 0].groupby(["season", "phase"], observed=False)["rpb"].mean().to_dict()
    phase_bowl_baseline = bowl[bowl["balls"] > 0].groupby(["season", "phase"], observed=False)["rpb_conceded"].mean().to_dict()

    def season_rpb_bat(season, pos, phase=None):
        if phase is not None:
            return float(phase_bat_baseline.get((season, phase), bat_league_baseline.get(season, 0.1417)))
        return float(pos_baseline.get((season, pos), bat_league_baseline.get(season, 0.1417)))

    def season_rpb_bowl(season, phase=None):
        if phase is not None:
            return float(phase_bowl_baseline.get((season, phase), bowl_league_baseline.get(season, 0.1417)))
        return float(bowl_league_baseline.get(season, 0.1417))

    def regress(r, frac):
        return float(elo_start + (r - elo_start) * (1 - frac))

    def dynamic_k(balls, match_count, form_std):
        base_k = 22.0
        experience_factor = max(0.4, 1.0 - match_count / 50)
        form_factor = 1.0 + min(0.5, form_std / 0.05)
        k = base_k * np.sqrt(max(balls, 1)) * experience_factor * form_factor
        return float(np.clip(k, k_min, k_max))

    all_rounder_ids = set(bat["player_id"]).intersection(set(bowl["player_id"]))

    def is_all_rounder(pid):
        return pid in all_rounder_ids

    bat_elo, bowl_elo = {}, {}
    last_seen_bat, last_seen_bowl = {}, {}
    match_counts_bat, match_counts_bowl = defaultdict(int), defaultdict(int)
    form_bat, form_bowl = defaultdict(list), defaultdict(list)
    cum_balls_bat, cum_balls_bowl = defaultdict(int), defaultdict(int)
    elo_rows = []

    matches = (
        pd.concat([bat[["match_id", "start_date"]], bowl[["match_id", "start_date"]]])
        .drop_duplicates()
        .sort_values("start_date")["match_id"]
    )

    for match_id in matches:
        match_bat = bat[bat["match_id"] == match_id]
        match_bowl = bowl[bowl["match_id"] == match_id]

        # ------------- Batting updates -------------
        for _, row in match_bat.iterrows():
            pid = row["player_id"]
            season = int(row["season"])
            balls = int(row["balls_faced"] or 0)
            runs = int(row["runs"] or 0)
            phase = row.get("phase")
            pos = int(row.get("batting_order_position") or 0)

            if per_match_min_balls is not None and balls < per_match_min_balls:
                pre = bat_elo.get(pid, elo_start)
                elo_rows.append(dict(
                    date=row["start_date"], season=season, match_id=match_id, player_id=pid, player_name=row["player_name"],
                    role="bat", balls=balls, runs=runs, base_rpb=season_rpb_bat(season, pos, phase),
                    opp_elo=np.nan, phase=phase, elo_pre=float(pre), elo_post=float(pre), delta=0.0,
                    cum_balls_before=cum_balls_bat[pid], cum_balls_after=cum_balls_bat[pid] + balls,
                ))
                cum_balls_bat[pid] += balls
                continue

            reached_gate_before = cum_balls_bat[pid] >= min_career_balls
            cum_balls_bat[pid] += balls

            bat_elo.setdefault(pid, elo_start)
            if last_seen_bat.get(pid) != season:
                bat_elo[pid] = regress(bat_elo[pid], season_regress)
                last_seen_bat[pid] = season

            opp_bowlers = match_bowl[match_bowl["team_id"] == row["opposition_team_id"]]
            avg_opp_elo = (
                opp_bowlers["player_id"].apply(lambda x: bowl_elo.get(x, elo_start)).mean()
                if not opp_bowlers.empty else elo_start
            )

            base_rpb = season_rpb_bat(season, pos, phase)
            actual_rpb = (runs / balls) if balls > 0 else 0.0
            expected_rpb = base_rpb * (10 ** ((bat_elo[pid] - avg_opp_elo) / scale))
            advantage = actual_rpb / max(1e-6, expected_rpb)
            S, E = advantage / (1 + advantage), 0.5

            form_std = np.std(form_bat[pid]) if len(form_bat[pid]) > 1 else 0.0
            k_scale = 0.85 if is_all_rounder(pid) else 1.0
            K = dynamic_k(balls, match_counts_bat[pid], form_std) * k_scale

            if not reached_gate_before and cum_balls_bat[pid] < min_career_balls:
                delta = 0.0
            else:
                delta = float(np.clip(K * (S - E), -max_delta, max_delta))

            pre = bat_elo[pid]
            bat_elo[pid] = pre + delta

            if balls > 0:
                form_bat[pid].append(actual_rpb)
                if len(form_bat[pid]) > form_window:
                    form_bat[pid] = form_bat[pid][-form_window:]
            match_counts_bat[pid] += 1

            elo_rows.append(dict(
                date=row["start_date"], season=season, match_id=match_id, player_id=pid, player_name=row["player_name"],
                role="bat", balls=balls, runs=runs, base_rpb=base_rpb, opp_elo=float(avg_opp_elo), phase=phase,
                elo_pre=float(pre), elo_post=float(bat_elo[pid]), delta=float(delta),
                cum_balls_before=cum_balls_bat[pid] - balls, cum_balls_after=cum_balls_bat[pid],
            ))

        # ------------- Bowling updates -------------
        for _, row in match_bowl.iterrows():
            pid = row["player_id"]
            season = int(row["season"])
            balls = int(row["balls"] or 0)
            runs = int(row["runs"] or 0)
            phase = row.get("phase")

            if per_match_min_balls is not None and balls < per_match_min_balls:
                pre = bowl_elo.get(pid, elo_start)
                elo_rows.append(dict(
                    date=row["start_date"], season=season, match_id=match_id, player_id=pid, player_name=row["player_name"],
                    role="bowl", balls=balls, runs=runs, base_rpb=season_rpb_bowl(season, phase),
                    opp_elo=np.nan, phase=phase, elo_pre=float(pre), elo_post=float(pre), delta=0.0,
                    cum_balls_before=cum_balls_bowl[pid], cum_balls_after=cum_balls_bowl[pid] + balls,
                ))
                cum_balls_bowl[pid] += balls
                continue

            reached_gate_before = cum_balls_bowl[pid] >= min_career_balls
            cum_balls_bowl[pid] += balls

            bowl_elo.setdefault(pid, elo_start)
            if last_seen_bowl.get(pid) != season:
                bowl_elo[pid] = regress(bowl_elo[pid], season_regress)
                last_seen_bowl[pid] = season

            opp_batters = match_bat[match_bat["team_id"] == row["opposition_team_id"]]
            avg_opp_elo = (
                opp_batters["player_id"].apply(lambda x: bat_elo.get(x, elo_start)).mean()
                if not opp_batters.empty else elo_start
            )

            base_rpb = season_rpb_bowl(season, phase)
            actual_rpb = (runs / balls) if balls > 0 else np.inf
            expected_rpb = base_rpb * (10 ** ((avg_opp_elo - bowl_elo[pid]) / scale))
            advantage = expected_rpb / max(1e-6, actual_rpb)
            S, E = advantage / (1 + advantage), 0.5

            form_std = np.std(form_bowl[pid]) if len(form_bowl[pid]) > 1 else 0.0
            k_scale = 0.85 if is_all_rounder(pid) else 1.0
            K = dynamic_k(balls, match_counts_bowl[pid], form_std) * k_scale

            if not reached_gate_before and cum_balls_bowl[pid] < min_career_balls:
                delta = 0.0
            else:
                delta = float(np.clip(K * (S - E), -max_delta, max_delta))

            pre = bowl_elo[pid]
            bowl_elo[pid] = pre + delta

            if balls > 0:
                form_bowl[pid].append(actual_rpb)
                if len(form_bowl[pid]) > form_window:
                    form_bowl[pid] = form_bowl[pid][-form_window:]
            match_counts_bowl[pid] += 1

            elo_rows.append(dict(
                date=row["start_date"], season=season, match_id=match_id, player_id=pid, player_name=row["player_name"],
                role="bowl", balls=balls, runs=runs, base_rpb=base_rpb, opp_elo=float(avg_opp_elo), phase=phase,
                elo_pre=float(pre), elo_post=float(bowl_elo[pid]), delta=float(delta),
                cum_balls_before=cum_balls_bowl[pid] - balls, cum_balls_after=cum_balls_bowl[pid],
            ))

    elo_df = pd.DataFrame(elo_rows).sort_values(["date", "player_id", "role"]).reset_index(drop=True)
    return elo_df
